# ==================== BROWSER CONFIG ====================
# Supported values: chrome, firefox, edge
browser=chrome

# Run browser without UI (ture for CI/CI pipelines)
headless=false

# ==================== APPLICATION CONFIG ====================
base.url=https://automationexercise.com

# ==================== TIMEOUT CONFIG (in seconds) ====================
# Explicit wait timeout - used for waiting specific elements
explicit.wait=10

# Page load timeout - max time out to wait for a page to fully load
page.load.timeout=30

# Implicit wait - global fallback wait (keep low to avoid masking issues)
implicit.wait=0